# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b6e3b072ba1d97f5493828d04a7d4acb72439c7313b91dfb50c78a79c85f217e4fd309fa7ecc4db5b51b11828084f63cbeafe3f86c376d2183eab3288d321c7

test:
  secret_key_base: c48d93a85d8bdc0e420ac009adab1308a1602827c4087279a1279571267e5381edec4e14ccb41a652135c8c626f2bbded7f23c3bca7a19933f24003797e4358a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
